apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aks-demo-tls
  namespace: aksdemo-nspace-d-01
spec:
  dnsNames:
    - frontend.52.188.222.60.nip.io
  secretName: aks-demo-tls-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

